name: Aaron Mahoney
favicon: null
layout_spectrum: 0.8784906498622149
typography_spectrum: 0.5920453267171979
title: Aaron Mahoney
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6104178829118609
  lightness: 0.23447080538608134
  saturation: 0.5775226070545614
  rhythmicContrast: 0.990544093074277
purpose: []
