analytics:
  twitter: null
  google: ' UA-72920433-1'
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.26387
title: Aaron Mahoney
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.625
  brandStrength: 0.5
  rhythmicContrast: 0.25
  brandColors:
    - '#040000'
    - '#fcfcfc'
    - '#5b1430'
    - '#d7a3c1'
    - '#983c69'
  lightness: 0
purpose: []
favicon: null
name: Aaron Mahoney
typography_spectrum: 0.5920453267171979
