name: Aaron Mahoney
favicon: null
layout_spectrum: 0.75913
typography_spectrum: 1
title: Aaron Mahoney
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: ' UA-72920433-1'
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#C6C5CD'
    - '#4E3928'
    - '#AC7072'
    - '#2C7A68'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
