title: Aaron Mahoney
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1734694
  brandStrength: 0.6104178829118609
  lightness: 0.2344708
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  rhythmicContrast: 0.9905441
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Aaron Mahoney
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5920453267171979
layout_spectrum: 0.8784906498622149
