name: Aaron Mahoney
favicon: null
layout_spectrum: 0.8784906498622149
typography_spectrum: 0.5920453267171979
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Aaron Mahoney
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: ' UA-72920433-1'
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6104178829118609
  lightness: 0.2344708
  saturation: 0.1734694
  rhythmicContrast: 0.9905441
purpose: []
